import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const config = {
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', ...builtins],
  format: 'cjs',
  target: 'es2016',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: prod ? 'dist/build/main.js' : 'dist/dev/main.js',
};

if (prod) {
  esbuild.build(config).catch(() => process.exit(1));
} else {
  const ctx = await esbuild.context(config);
  await ctx.watch();
}
